feat: диплом, часть 1, попытка 1.
misandr/java-explore-with-me pull request #3
Opened 2023-04-16 17:18 UTC by misandr

2023-04-17 16:14 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо в целом. Давай обсудим пару мест и поправим по комментариям и будет зачет.

2023-04-17 16:14 UTC, krylov-sergey-sergeevich commented on pom.xml
> +        <module>ewm</module>
стиль поехал

2023-04-17 16:14 UTC, krylov-sergey-sergeevich commented on stats/app.sh
> +java -jar /service-app.jar &
Для чего это?

2023-04-17 16:14 UTC, krylov-sergey-sergeevich commented on stats/pom.xml
> +        <relativePath>../pom.xml</relativePath>
это прям нужно?

2023-04-17 16:14 UTC, krylov-sergey-sergeevich commented on stats/service/src/main/java/ru/practicum/explore/stats/HitMapper.java
> +    public static Hit toHit(HitDto hitDto) {
стиль поехал в классе

2023-04-17 16:14 UTC, krylov-sergey-sergeevich commented on stats/service/src/main/java/ru/practicum/explore/stats/StatsController.java
> +    public Set<VisitDto> getStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
"yyyy-MM-dd HH:mm:ss" - повторяется

2023-04-17 18:10 UTC, misandr commented on stats/service/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits;
Это я постараюсь реализовать во время следующего этапа. Идею вроде понял.

2023-04-18 20:24 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-04-20 17:13 UTC, merged