feat: диплом, часть 2, попытка 1.
misandr/java-explore-with-me pull request #4
Opened 2023-04-24 22:07 UTC by misandr

2023-04-26 07:37 UTC, krylov-sergey-sergeevich requested changes
Привет, все хорошо, пару моментов давай обсудим и будет зачет

2023-04-26 07:37 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +        <maven.test.skip>true</maven.test.skip>
зачем?

2023-04-26 14:40 UTC, misandr commented on ewm/pom.xml
> +        <maven.test.skip>true</maven.test.skip>
Я до конца не понял, как правильно, разделить подключение баз для работы и для теста. В итоге создал отдельный файл application.properties для тестирования.

2023-04-26 14:44 UTC, misandr commented on ewm/src/main/java/ru/practicum/explore/service/CategoryService.java
> +            throw new ValidationException("Category didn't save!");
В задание написано, что должен быть CONFLICT. Но с такой ошибкой не проходит тест в postman: "Ответ должен содержать код статуса 400 и данные в формате json". В итоге пришлось так сделать)

2023-04-27 06:40 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2023-04-27 06:40 UTC, krylov-sergey-sergeevich commented on ewm/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
project.version можно использовать

2023-04-27 06:40 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/explore/service/CategoryService.java
> +            throw new ValidationException("Category didn't save!");
Понял, но выглядит все равно не очень, может подумать о исключение с другим названием но чтобы был Conflict

2023-04-27 17:26 UTC, merged