feat: диплом, часть 3, comments, попытка 1.
misandr/java-explore-with-me pull request #5
Opened 2023-04-29 14:46 UTC by misandr

2023-05-01 08:36 UTC, krylov-sergey-sergeevich requested changes
Привет

В целом неплохо, давай поправим что отметил и будет зачет =)

2023-05-01 08:36 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/explore/controller/PrivateController.java
> +
А тут нам еще не пригодится delete comment?

2023-05-01 08:36 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/explore/controller/PublicController.java
> +
Давай выделим все связанное с комментариями в отдельный контроллер и там посмотрим на него и подумаем какие методы были бы полезны

crud - как намек и совет

2023-05-01 08:36 UTC, krylov-sergey-sergeevich commented on ewm/src/main/java/ru/practicum/explore/model/Comment.java
> +    private LocalDateTime created;
Можно подумать еще про editedDate

2023-05-01 15:40 UTC, misandr commented on ewm/src/main/java/ru/practicum/explore/controller/PrivateController.java
> +
Я полагал, что закрытие запроса происходит, когда событие ещё не произошло. Поэтому считал, что комментариев ещё быть не может.

2023-05-02 16:23 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-05-03 10:08 UTC, merged